import { useState } from "react";

const DARK = "#1A1A1A";
const CHARCOAL = "#2E2E2E";
const GOLD = "#C4A84A";
const GOLD_LT = "#FAF4E3";
const GOLD_DK = "#8B7A2E";
const GREEN = "#3C870E";
const GREEN_LT = "#EAF3E3";
const GREEN_DK = "#2A5E0A";
const BLUE = "#1A5CAA";
const BLUE_LT = "#EAF0FB";
const GRAY = "#888888";
const LGRAY = "#F4F4F4";
const MGRAY = "#CCCCCC";
const WHITE = "#FFFFFF";
const ORANGE = "#CC4A18";
const ORANGE_LT = "#FFF0EA";

const sections = [
  {
    id: "overview",
    icon: "🗺️",
    label: "Overview",
    title: "How SocialBee Works for SEMAJ Media",
    color: GOLD,
    content: `SocialBee is built around one core idea: organize content into categories, assign each category a posting schedule, and let the platform run continuously.

The two post types that matter for your setup:

EVERGREEN — Posts that recycle automatically. SocialBee publishes the post, then moves it to the back of the queue. When the queue completes a full cycle, it starts again from the top. These run forever until you pause or delete them.

SHARE ONCE — Posts that fire once and expire. Marblism.ai campaign content, time-sensitive promotions, workshop announcements, and anything with a specific date goes here.

The system that works for you: Evergreen categories run continuously as your always-on baseline. Share Once posts from Marblism.ai campaigns layer on top without disturbing the evergreen loop.`
  },
  {
    id: "categories",
    icon: "📂",
    label: "Categories",
    title: "Setting Up Your Content Categories",
    color: BLUE,
    content: `Categories are the foundation. Every post lives inside one. Each category gets its own posting schedule and its own evergreen or share-once setting.

BUILD THESE CATEGORIES FIRST:

Heyward CPA — Evergreen
Tax tips, financial literacy, business finance insights. The backbone of the Heyward CPA social presence. Posts recycle continuously.

BYOBookkeeper — Evergreen
Bookkeeping education, BYOB philosophy, service positioning. Recycles continuously.

Financial Flipside — Evergreen
Newsletter content, financial mindset posts, money culture. Recycles continuously.

HCPA Live — Share Once
Episode announcements, show promos, post-show recaps. Fires once per post — never repeats.

Marblism Campaigns — Share Once
Content generated by Marblism.ai for specific campaigns. Fires once per post. Never set these to evergreen — campaigns have a message arc that should not repeat out of context.

Promotional — Share Once
Workshop announcements, consultation CTAs, time-sensitive offers. Fires once.

HOW TO CREATE A CATEGORY:
1. Go to Content Categories in the left sidebar
2. Click Create Category
3. Name it (e.g. Heyward CPA — Evergreen)
4. Click Default Settings
5. Toggle Re-queue after posting ON for evergreen categories, OFF for share-once
6. Click Save`
  },
  {
    id: "evergreen",
    icon: "🔁",
    label: "Evergreen Loop",
    title: "Building the Evergreen Recycling Loop",
    color: GREEN,
    content: `This is the core of what you want: continuous posting that requires no ongoing manual work.

HOW THE LOOP WORKS:
SocialBee publishes Post 1 from a category → moves it to the back of the queue → publishes Post 2 → ... → publishes the last post → jumps back to Post 1 and starts again. The loop never stops unless you pause it.

SETTING UP AN EVERGREEN CATEGORY:
1. Create a category and enable Re-queue after posting in Default Settings
2. Add posts to the category (see Adding Posts section)
3. Each post will automatically re-queue after publishing
4. The category runs indefinitely

MINIMUM CONTENT FOR A HEALTHY LOOP:
With a daily posting schedule, you need enough posts so the same content doesn't repeat too frequently. Rule of thumb: at minimum 30 posts per evergreen category before activating. At 30 posts posting once daily, each post recycles roughly once per month — acceptable. At 60 posts, once every two months — ideal.

POST VARIATIONS — the key to keeping evergreen content fresh:
Each evergreen post can have multiple variations. SocialBee publishes one variation per cycle. So one "topic" can have 3-4 different versions of the caption or image, and the audience sees something different each time it recycles.

To add variations:
1. Open any post in the editor
2. Click Add Variation at the bottom
3. Write a different version of the caption (same topic, different angle or wording)
4. Add a different image if desired
5. Save

In Cycle 1: Variation 1 publishes
In Cycle 2: Variation 2 publishes
In Cycle 3: Variation 3 publishes
Then back to Variation 1

This is how 30 posts with 3 variations each becomes effectively 90 unique posts — without writing 90 posts.

IMPORTANT — Post order in evergreen categories:
New posts added to an evergreen category go to the TOP of the queue by default (newest first). This means fresh content publishes first and older posts gradually cycle back in. If you want to post in a specific order, change the category to FIFO (oldest first) in settings.`
  },
  {
    id: "marblism",
    icon: "🤖",
    label: "Marblism Campaigns",
    title: "How Marblism.ai Campaigns Fit In",
    color: ORANGE,
    content: `Marblism.ai generates campaign-specific content — posts with a defined message arc, a goal, and a sequence. These should NEVER go into an evergreen category because campaign posts are designed to build on each other in order. Recycling them out of context breaks the arc and confuses the audience.

THE RIGHT SETUP FOR MARBLISM CONTENT:

Use a dedicated Share Once category for each campaign. Name it clearly:
  — Marblism | BYOB Workshop April 2026
  — Marblism | Financial Flipside Launch
  — Marblism | Tax Strategy Q2 2026

Each campaign gets its own category. When the campaign is done, pause or archive the category — it doesn't affect any other queue.

HOW TO IMPORT MARBLISM CONTENT INTO SOCIALBEE:

Option 1 — Manual paste (for small campaigns):
1. Copy each post from Marblism.ai
2. Add post in SocialBee → paste caption → attach image if provided
3. Set to Share Once
4. Schedule at specific date/time OR add to queue bottom
5. Repeat for each post in the campaign

Option 2 — CSV bulk import (for large campaigns):
1. Export your Marblism campaign posts to a spreadsheet
2. Format as CSV: columns for date, time, caption, image URL, platform
3. In SocialBee go to Content Categories → your campaign category
4. Click Import → CSV
5. Upload the file — all posts import at once with their schedule

Option 3 — RSS or Zapier (for automated handoff):
If Marblism.ai supports RSS output or Zapier integration, you can connect it directly to SocialBee so approved campaign posts flow in automatically.

CAMPAIGN SCHEDULING STRATEGY:
Do not let Marblism campaign posts compete with evergreen posts on the same time slot. Set campaign post times to DIFFERENT slots than your evergreen schedule. The evergreen loop fills the baseline. Campaign posts run in addition — not instead of.

EXAMPLE: Evergreen posts at 9am and 3pm. Campaign posts at 12pm and 6pm. The audience gets 4 posts per day — 2 from the always-on evergreen loop, 2 from the active campaign.`
  },
  {
    id: "schedule",
    icon: "📅",
    label: "Schedule Setup",
    title: "Building Your Posting Schedule",
    color: CHARCOAL,
    content: `The schedule tells SocialBee when to pull from each category. Each time slot is assigned to one specific category. Multiple time slots can pull from the same category.

HOW TO SET UP A SCHEDULE:
1. Go to Schedule Setup in the left sidebar
2. Select a social media profile (e.g. LinkedIn Personal — James)
3. Click a time slot on the calendar grid
4. Select which category to pull from at that time
5. Repeat for each day and time you want to post

RECOMMENDED SCHEDULE FOR SEMAJ MEDIA:

LinkedIn Personal (James) — 5x per week
  Mon 8am → Heyward CPA Evergreen
  Tue 8am → Financial Flipside Evergreen
  Wed 8am → Heyward CPA Evergreen
  Thu 8am → BYOBookkeeper Evergreen
  Fri 8am → Heyward CPA Evergreen
  [Campaign posts: 12pm slots when a Marblism campaign is active]

Facebook Page (Heyward CPA) — 4x per week
  Mon 10am → Heyward CPA Evergreen
  Wed 10am → BYOBookkeeper Evergreen
  Thu 10am → HCPA Live (show week) or Heyward CPA Evergreen
  Sat 10am → Heyward CPA Evergreen

Instagram — 4x per week
  Tue 11am → Heyward CPA Evergreen
  Thu 11am → BYOBookkeeper Evergreen
  Sat 11am → Financial Flipside Evergreen
  Sun 11am → Heyward CPA Evergreen

X (Twitter) — 5x per week
  Daily 9am → rotate between Heyward CPA, Flipside, BYOBookkeeper evergreen

IMPORTANT RULE: Each time slot pulls the NEXT post in that category's queue. So if the Monday 8am LinkedIn slot is assigned to Heyward CPA Evergreen, it will always publish the next post in that category's queue — automatically, continuously, without any action from you.`
  },
  {
    id: "adding",
    icon: "✍️",
    label: "Adding Posts",
    title: "Adding Posts to SocialBee",
    color: GOLD,
    content: `Four ways to get content into SocialBee. Use all four depending on the content type.

METHOD 1 — Add Post (manual, one at a time):
Best for: individual posts, custom content, anything that needs specific attention
1. Click Add Post in the top bar or left sidebar
2. Select which social profiles this post goes to
3. Write the caption (or paste from Marblism or Claude)
4. Attach image or video
5. Customize per platform using the platform tabs — LinkedIn caption can be different from Instagram
6. Select the content category
7. Set to Re-queue (evergreen) or Share Once
8. Set posting time: Now, Specific Time, Add to Queue Top, or Add to Queue Bottom
9. Click Save as Approved

METHOD 2 — Bulk import via CSV:
Best for: Marblism campaign batches, large content loads
Format: date, time, caption, image URL, platform, category
Import via Content Categories → Import → CSV

METHOD 3 — RSS feed import:
Best for: auto-importing blog posts from heywardcpa.com or Financial Flipside
1. Get the RSS URL from your WordPress blog or Substack
2. In SocialBee go to Import → RSS
3. Paste the RSS URL
4. Choose which category new posts go to
5. SocialBee auto-creates posts whenever a new article publishes

METHOD 4 — Bulk edit across a category:
Best for: updating CTAs, links, or hashtags across multiple posts at once
1. Go to the Content Category
2. Select multiple posts using the checkboxes
3. Click Bulk Edit
4. Update what you need across all selected posts simultaneously

PLATFORM CUSTOMIZATION (critical for Instagram):
Instagram does not allow links in captions. LinkedIn does. Facebook does. When adding a post, use the per-platform tabs to:
  — Remove the link from the Instagram version, add "Link in bio" instead
  — Keep the full link in LinkedIn and Facebook versions
  — Adjust hashtag volume (Instagram: 5-10 tags, LinkedIn: 2-3, X: 1-2)`
  },
  {
    id: "workflow",
    icon: "⚡",
    label: "Workflow",
    title: "The Weekly Workflow with Marblism Running",
    color: GREEN,
    content: `This is the actual week-to-week operating procedure once everything is set up.

THE BASELINE (ongoing, no weekly action required):
Your evergreen categories run continuously. SocialBee posts from them automatically every day according to your schedule. You do nothing. The loop handles it.

WHEN A MARBLISM CAMPAIGN IS ACTIVE:
Week before campaign launches:
  1. Export Marblism campaign posts
  2. Create a new Share Once category for the campaign
  3. Import posts (CSV or manual)
  4. Assign campaign posts to 12pm slots (or your chosen campaign time)
  5. Approve all posts in the category
  6. Done — campaign runs automatically on schedule

During the campaign:
  — Evergreen posts continue at their normal times
  — Campaign posts fire at their campaign times
  — No daily management needed

After the campaign ends:
  1. Go to the campaign category
  2. Pause or archive it
  3. Evergreen loop continues unaffected

WHEN A NEW SHOW EPISODE PUBLISHES (Heyward CPA Live):
1. Add the episode promo post to HCPA Live — Share Once category
2. Set posting time to the day before or day of the episode
3. Add 2-3 clip posts after the episode (set to specific dates)
4. These fire once and expire — the evergreen loop continues around them

MONTHLY MAINTENANCE (30 minutes):
  — Review which evergreen posts are recycling most
  — Add 5-10 new evergreen posts to keep the library fresh
  — Check that no expired posts are creating gaps in the queue
  — Review analytics: which categories and posts drive the most engagement

CONTENT FROM CLAUDE TO SOCIALBEE:
When Claude generates social posts (like the BYOB workshop posts), the workflow is:
  1. Copy the post from Claude
  2. Open SocialBee Add Post
  3. Paste into the caption field
  4. Select profiles, customize per platform
  5. Assign to the right category (evergreen or campaign)
  6. Save as Approved`
  },
  {
    id: "analytics",
    icon: "📊",
    label: "Analytics",
    title: "Tracking What Works",
    color: BLUE,
    content: `SocialBee's analytics show you what's landing so you can load more of it into the evergreen loop.

WHERE TO FIND IT:
Left sidebar → Analyze → choose a profile or overview

KEY METRICS TO WATCH:
Post Performance — which individual posts get the most engagement
Category Performance — which category drives the most reach and clicks
Best Time to Post — when your audience is most active (use this to adjust your schedule)
Profile Growth — follower change over time per platform

THE EVERGREEN ADVANTAGE IN ANALYTICS:
Because posts recycle, you can see cumulative engagement across multiple cycles of the same post. A post with 50 likes in cycle 1 and 60 likes in cycle 2 is performing better over time — keep it. A post with 50 likes in cycle 1 and 10 likes in cycle 2 — retire it and replace with something stronger.

WHAT TO DO WITH THE DATA:
High performing evergreen post → add 2 more variations to it so it stays in rotation longer with fresh angles
Low performing evergreen post → either add a variation with a different approach, or expire and replace
High performing category → add more posts to it
Campaign post outperforming evergreen → consider pulling that topic into the evergreen rotation as a standalone post

SOCIALBEE + MARBLISM FEEDBACK LOOP:
When you see which types of Marblism campaign posts perform well in SocialBee analytics, feed that back to Marblism as context for the next campaign. "Posts that lead with a pain point question outperform posts that lead with a solution statement" — that's campaign intelligence that makes the next Marblism output better.`
  }
];

export default function SocialBeeGuide() {
  const [active, setActive] = useState("overview");
  const current = sections.find(s => s.id === active);

  const formatContent = (text) => {
    return text.split("\n\n").map((block, i) => {
      const lines = block.split("\n");
      const isHeader = lines[0] === lines[0].toUpperCase() && lines[0].length > 3 && !lines[0].startsWith(" ") && lines[0].endsWith(":");
      const isList = lines.some(l => l.startsWith("  —") || l.startsWith("  1.") || l.startsWith("  2.") || l.match(/^\s+\d\./));

      if (isHeader) {
        return (
          <div key={i} style={{ marginBottom: 16 }}>
            <div style={{ fontSize: 11, fontWeight: 500, color: GOLD_DK, letterSpacing: "0.12em", marginBottom: 8 }}>
              {lines[0].replace(":", "")}
            </div>
            {lines.slice(1).map((l, j) => (
              <p key={j} style={{ fontSize: 14, color: CHARCOAL, lineHeight: 1.6, margin: "4px 0" }}>{l}</p>
            ))}
          </div>
        );
      }

      return (
        <div key={i} style={{ marginBottom: 14 }}>
          {lines.map((line, j) => {
            const isIndented = line.startsWith("  —") || line.match(/^\s+\d\./) || line.startsWith("  ");
            const isBold = line.includes("→") || line.startsWith("IMPORTANT") || line.startsWith("Option");
            return (
              <p key={j} style={{
                fontSize: 14,
                color: isIndented ? "#555" : CHARCOAL,
                lineHeight: 1.65,
                margin: "3px 0",
                paddingLeft: isIndented ? 16 : 0,
                fontWeight: isBold ? 500 : 400,
              }}>
                {line}
              </p>
            );
          })}
        </div>
      );
    });
  };

  return (
    <div style={{ fontFamily: "Arial, sans-serif", background: "#EBEBEB", minHeight: "100vh", paddingBottom: 40 }}>

      {/* Header */}
      <div style={{ background: DARK, padding: "20px 24px 18px", borderBottom: "4px solid " + GOLD }}>
        <div style={{ fontSize: 10, fontWeight: 500, color: GOLD, letterSpacing: "0.3em", marginBottom: 6 }}>
          SEMAJ MEDIA  ·  SOCIALBEE GUIDE
        </div>
        <div style={{ fontSize: 22, fontWeight: 500, color: WHITE, lineHeight: 1.15, marginBottom: 2 }}>
          SocialBee: Continuous Posting
        </div>
        <div style={{ fontSize: 22, fontWeight: 500, color: GOLD, lineHeight: 1.15, marginBottom: 10 }}>
          with Marblism.ai Campaigns
        </div>
        <div style={{ fontSize: 12, color: "#AAAAAA" }}>
          Evergreen loops, campaign integration, and the weekly workflow for Heyward CPA and Financial Flipside.
        </div>
      </div>

      {/* Nav */}
      <div style={{ background: WHITE, borderBottom: "1px solid #DDDDDD", overflowX: "auto" }}>
        <div style={{ display: "flex", minWidth: "max-content" }}>
          {sections.map(s => (
            <button key={s.id} onClick={() => setActive(s.id)} style={{
              padding: "12px 16px", border: "none", background: "none", cursor: "pointer",
              fontSize: 12, fontWeight: 500,
              color: active === s.id ? s.color : GRAY,
              borderBottom: active === s.id ? "3px solid " + s.color : "3px solid transparent",
              whiteSpace: "nowrap",
              transition: "all 0.15s"
            }}>
              {s.icon} {s.label}
            </button>
          ))}
        </div>
      </div>

      {/* Content */}
      {current && (
        <div style={{ padding: "20px 24px" }}>
          <div style={{ background: WHITE, borderRadius: 10, overflow: "hidden", boxShadow: "0 2px 8px rgba(0,0,0,0.08)" }}>

            {/* Section header */}
            <div style={{ background: current.color, padding: "16px 20px" }}>
              <div style={{ fontSize: 18, fontWeight: 500, color: WHITE }}>{current.title}</div>
            </div>

            {/* Section body */}
            <div style={{ padding: "20px 24px" }}>
              {formatContent(current.content)}
            </div>
          </div>

          {/* Quick reference card */}
          <div style={{ background: WHITE, borderRadius: 10, marginTop: 14, overflow: "hidden", boxShadow: "0 2px 8px rgba(0,0,0,0.08)" }}>
            <div style={{ background: DARK, padding: "11px 20px" }}>
              <span style={{ fontSize: 10, fontWeight: 500, color: GOLD, letterSpacing: "0.2em" }}>QUICK REFERENCE</span>
            </div>
            <div style={{ display: "flex", flexWrap: "wrap", gap: 0 }}>
              {[
                ["Evergreen categories", "Recycle automatically, run forever, need 30+ posts minimum"],
                ["Share Once categories", "Fire once and expire — use for all Marblism campaigns"],
                ["Post Variations", "Add 2–4 versions per evergreen post — different caption each cycle"],
                ["Campaign import", "CSV bulk import for Marblism batches, separate category per campaign"],
                ["Schedule slots", "Each slot = one category — evergreen and campaign slots should not overlap"],
                ["Platform tabs", "Customize caption per platform — remove links for Instagram"],
              ].map(([label, value], i) => (
                <div key={i} style={{
                  width: "50%", boxSizing: "border-box",
                  padding: "11px 20px",
                  background: i % 4 < 2 ? GOLD_LT : LGRAY,
                  borderBottom: i < 4 ? "1px solid #EEEEEE" : "none",
                  borderRight: i % 2 === 0 ? "1px solid #EEEEEE" : "none",
                }}>
                  <div style={{ fontSize: 11, fontWeight: 500, color: GOLD_DK, marginBottom: 3 }}>{label}</div>
                  <div style={{ fontSize: 12, color: CHARCOAL, lineHeight: 1.4 }}>{value}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
